name: HeadLimiter
version: ${project.version}
main: dev.j3fftw.headlimiter.HeadLimiter
depend: [Slimefun]
api-version: 1.16

commands:
  headlimiter:
    description: Basic HeadLimiter command
    aliases: hl

permissions:
  headlimiter.bypass:
    description: Allows players to bypass the head limit
    default: false